services:
  #  PostgreSQL – Primary relational datastore
  postgres:
    image: postgres:16-alpine
    container_name: cinerate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cinerate_user
      POSTGRES_PASSWORD: cinerate_pass
      POSTGRES_DB: cinerate_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cinerate_user -d cinerate_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  #  Redis – Caching layer (Top-10 movies, etc.)
  redis:
    image: redis:7-alpine
    container_name: cinerate-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
