CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- reset tablesDROP TABLE IF EXISTS watchlist CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- usersCREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    last_username_change_at TIMESTAMP,
    last_email_change_at TIMESTAMP,
    last_password_change_at TIMESTAMP
);

-- moviesCREATE TABLE movies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(200) NOT NULL,
    synopsis TEXT NOT NULL DEFAULT '',
    director VARCHAR(120) NOT NULL DEFAULT 'Unknown',
    release_year INT NOT NULL CHECK (release_year >= 1888),
    poster_url TEXT NOT NULL DEFAULT '',
    genres VARCHAR[] NOT NULL DEFAULT '{}'
);

-- reviews (rating in 0.5 increments from 0.5 to 5)CREATE TABLE reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    movie_id UUID NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    review_text TEXT DEFAULT '',
    rating NUMERIC(2,1) NOT NULL CHECK (rating >= 0.5 AND rating <= 5 AND (rating * 2)::int = (rating * 2)),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, movie_id)
);

CREATE INDEX idx_reviews_movie ON reviews(movie_id);
CREATE INDEX idx_reviews_user ON reviews(user_id);

-- watchlistCREATE TABLE watchlist (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    movie_id UUID NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    added_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, movie_id)
);

CREATE INDEX idx_watchlist_user ON watchlist(user_id);

-- seed users (password for all is "password123", bcrypt-hashed)INSERT INTO users (id, username, email, password_hash) VALUES
    ('11111111-1111-1111-1111-111111111111', 'fahreza', 'fahreza@cinerate.io', '$2b$12$i/KSFTcmgkusl8t9BzAYx.kErXHgewTf16cXatWpb0lAAS.5C9gQW'),
    ('22222222-2222-2222-2222-222222222222', 'jarkon',  'jarkon@cinerate.io',  '$2b$12$f6pDuTYJfZnc3qnfZ33.rewM/oL1aKPPcm1/igRefFsqTVafG6w/S'),
    ('33333333-3333-3333-3333-333333333333', 'brogib',  'brogib@cinerate.io',  '$2b$12$iSL75UuTYagFcuNrqIsz.Oce5Hraeg39yPd.rjXPhVoD8Ep6Iy2ES'),
    ('44444444-4444-4444-4444-444444444444', 'abed',    'abed@cinerate.io',    '$2b$12$A/eF48zLEhHMgqFjdshhMub8zz6LPRKiGeHWlSu3RZmHdht9MvIOa'),
    ('55555555-5555-5555-5555-555555555555', 'gibkon',  'gibkon@cinerate.io',  '$2b$12$dDcXphokTqCyQfOLdpnePuwwWLq0YM29BofxP76R9z5rfre4s7tje');

-- seed moviesINSERT INTO movies (id, title, synopsis, director, release_year, poster_url, genres) VALUES
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.', 'Francis Ford Coppola', 1972, 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', ARRAY['Crime', 'Drama']),
    ('cccccccc-cccc-cccc-cccc-cccccccccccc', 'The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Frank Darabont', 1994, 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', ARRAY['Drama', 'Crime']),
    ('dddddddd-dddd-dddd-dddd-dddddddddddd', 'The Dark Knight', 'When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.', 'Christopher Nolan', 2008, 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', ARRAY['Action', 'Crime', 'Drama']),
    ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'Inception', 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.', 'Christopher Nolan', 2010, 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', ARRAY['Action', 'Sci-Fi', 'Thriller']),
    ('ffffffff-ffff-ffff-ffff-ffffffffffff', 'Parasite', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 'Bong Joon-ho', 2019, 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', ARRAY['Drama', 'Thriller', 'Comedy']),
    ('1a1a1a1a-1a1a-1a1a-1a1a-1a1a1a1a1a1a', 'Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'Christopher Nolan', 2014, 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', ARRAY['Adventure', 'Drama', 'Sci-Fi']),
    ('2b2b2b2b-2b2b-2b2b-2b2b-2b2b2b2b2b2b', 'Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'Quentin Tarantino', 1994, 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', ARRAY['Crime', 'Drama', 'Thriller']),
    ('4d4d4d4d-4d4d-4d4d-4d4d-4d4d4d4d4d4d', 'The Matrix', 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers.', 'The Wachowskis', 1999, 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', ARRAY['Action', 'Sci-Fi']),
    ('5e5e5e5e-5e5e-5e5e-5e5e-5e5e5e5e5e5e', 'Spider-Man: Into the Spider-Verse', 'Teen Miles Morales becomes Spider-Man of his reality, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.', 'Bob Persichetti', 2018, 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', ARRAY['Animation', 'Action', 'Adventure']),
    ('6f6f6f6f-6f6f-6f6f-6f6f-6f6f6f6f6f6f', 'Dune', 'Feature adaptation of Frank Herbert''s science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset in the galaxy.', 'Denis Villeneuve', 2021, 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg', ARRAY['Action', 'Adventure', 'Sci-Fi']),
    ('174bb43d-a210-44dc-9611-6f84fdc29515', '2001: A Space Odyssey', '"2001" is a story of evolution. Sometime in the distant past, someone or something nudged evolution by placing a monolith on Earth (presumably elsewhere throughout the universe as well). Evolution then enabled humankind to reach the moon''s surface, where yet another monolith is found, one that signals the monolith placers that humankind has evolved that far. Now a race begins between computers (HAL) and human (Bowman) to reach the monolith placers. The winner will achieve the next step in evolution, whatever that may be.', 'Stanley Kubrick', 1968, 'https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29.png', ARRAY['Adventure', 'Sci-Fi']),
    ('67f84570-7e15-4500-a63d-97b17e4c02ac', 'Blade Runner', 'In the early twenty-first century, the Tyrell Corporation, during what was called the Nexus phase, developed robots, called "replicants", that were supposed to aid society, the replicants which looked and acted like humans. When the superhuman generation Nexus 6 replicants, used for dangerous off-Earth endeavors, began a mutiny on an off-Earth colony, replicants became illegal on Earth. Police units, called "blade runners", have the job of destroying - or in their parlance "retiring" - any replicant that makes its way back to or created on Earth, with anyone convicted of aiding or assisting a replicant being sentenced to death. It''s now November, 2019 in Los Angeles, California. Rick Deckard, a former blade runner, is called out of retirement when four known replicants, most combat models, have made their way back to Earth, with their leader being Roy Batty. One, Leon Kowalski, tried to infiltrate his way into the Tyrell Corporation as an employee, but has since been able to escape. Beyond following Leon''s trail in hopes of finding and retiring them all, Deckard believes part of what will help him is figuring out what the replicants wanted with the Tyrell Corporation in trying to infiltrate it. The answer may lie with Tyrell''s fail-safe backup mechanism. Beyond tracking the four, Deckard faces a possible dilemma in encountering a fifth replicant: Rachael, who works as Tyrell''s assistant. The issue is that Dr. Elden Tyrell is experimenting with her, to provide her with fake memories so as to be able to better control her. With those memories, Rachael has no idea that she is not human. The problem is not only Rachael''s assistance to Deckard, but that he is beginning to develop feelings for her.', 'Ridley Scott', 1982, 'https://upload.wikimedia.org/wikipedia/en/9/9f/Blade_Runner_%281982_poster%29.png', ARRAY['Sci-Fi', 'Thriller']),
    ('5562ad14-dcb0-414a-96d7-635b6dc6178c', 'Blade Runner 2049', 'Thirty years after the events of Blade Runner (1982), a new Blade Runner, L.A.P.D. Officer "K" (Ryan Gosling), unearths a long-buried secret that has the potential to plunge what''s left of society into chaos. K''s discovery leads him on a quest to find Rick Deckard (Harrison Ford), a former L.A.P.D. Blade Runner, who has been missing for thirty years.', 'Denis Villeneuve', 2017, 'https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png', ARRAY['Action', 'Drama', 'Sci-Fi']),
    ('cb169251-5550-4abc-acbe-80e3fe27d08c', 'Ex Machina', 'Caleb, a 26 year old programmer at the world''s largest internet company, wins a competition to spend a week at a private mountain retreat belonging to Nathan, the reclusive CEO of the company. But when Caleb arrives at the remote location he finds that he will have to participate in a strange and fascinating experiment in which he must interact with the world''s first true artificial intelligence, housed in the body of a beautiful robot girl.', 'Alex Garland', 2014, 'https://upload.wikimedia.org/wikipedia/en/b/ba/Ex-machina-uk-poster.jpg', ARRAY['Drama', 'Sci-Fi', 'Thriller']),
    ('2d058648-7fb6-4850-a4a4-9e0130f213ee', 'Arrival', 'Linguistics professor Louise Banks leads an elite team of investigators when gigantic spaceships touchdown in 12 locations around the world. As nations teeter on the verge of global war, Banks and her crew must race against time to find a way to communicate with the extraterrestrial visitors. Hoping to unravel the mystery, she takes a chance that could threaten her life and quite possibly all of mankind.', 'Denis Villeneuve', 2016, 'https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg', ARRAY['Drama', 'Sci-Fi', 'Mystery']),
    ('155017c7-9dc4-4b43-a321-f62f4aaec1a8', 'The Terminator', 'Sent back from a dystopian 2029--where the cold machines have conquered the entire world--to 1984 Los Angeles, the indestructible cyborg-assassin known as the "Terminator" commences his deadly mission to kill humankind''s most important woman: the unsuspecting Sarah Connor. However, from the same war-torn post-apocalyptic future comes a battle-scarred defender--Kyle Reese, a brave soldier of the human Resistance Army--bent on stopping the cybernetic killer from eliminating the world''s last hope. But, the Terminator has no feelings, he doesn''t sleep, and above all, he won''t stop until he carries out his grim task. Does our future lie in our past?', 'James Cameron', 1984, 'https://upload.wikimedia.org/wikipedia/en/6/6d/The_Terminator.png', ARRAY['Action', 'Sci-Fi', 'Thriller']),
    ('8ce2dcd5-4afd-43dd-bfe3-d869729261ab', 'Children of Men', 'London, 2027. In this dystopian world, humans have been incapable of reproducing for eighteen years for an unknown reason, meaning the imminent extinction of the species. Britain is the one remaining civilized society on the planet, which has resulted in people wanting to immigrate there. As such, it has become a police state in order to handle the immigrants, who are placed into refugee camps. Lowly government bureaucrat Theo Faron, once an activist, is approached by the Fishes, deemed a terrorist group, led by his ex-wife Julian Taylor, who he has not seen in close to twenty years, their marriage which disintegrated following the death of their infant son Dylan during the 2008 flu pandemic. Although the Fishes did use terrorist means in their on-going revolution against the state in the fight for immigrant rights, Julian vows that they now garner support solely by speaking to the people. What she wants is for Theo to use his connections to get transit papers for a young immigrant woman named Kee who needs to get to the coast. Although initially reluctant to do it because of the difficulty, Theo is able to grant Julian this favor, however with the change that he now needs to accompany Kee on her journey. As Theo and Kee progress on that journey, Theo learns more and more about what''s going on, including the reason that Kee needs to get to the coast, the fact that no one in the group knows if their end destination even exists, and that his and Kee''s lives are in greater danger than he believed when they started the journey. But Theo''s sole mission becomes to help Kee at any cost for the survival of the species.', 'Alfonso Cuarón', 2006, 'https://upload.wikimedia.org/wikipedia/en/f/fc/Children_of_men_ver4.jpg', ARRAY['Action', 'Drama', 'Sci-Fi']),
    ('f94a50ad-516b-4060-b8e0-b0fbda69ecc6', 'Goodfellas', 'Henry Hill recounts his life in the mob, from his teenage years to his eventual downfall. Immersed in organized crime, he experiences wealth, power, and violence alongside friends Jimmy Conway and Tommy DeVito. The film blends crime, drama, and dark humor, exploring loyalty, ambition, betrayal, and the consequences of criminal life. Themes of family, morality, and the fleeting nature of power underpin the story.', 'Martin Scorsese', 1990, 'https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg', ARRAY['Biography', 'Crime', 'Drama']),
    ('cad765ee-ff98-4e2e-8b14-58125f472b23', 'The Godfather Part II', 'The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'Francis Ford Coppola', 1974, 'https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg', ARRAY['Crime', 'Drama']),
    ('bf6d8a93-d36c-43f1-b52f-71b26e0f8e16', 'No Country for Old Men', 'In rural Texas, welder and hunter Llewelyn Moss (Josh Brolin) discovers the remains of several drug runners who have all killed each other in an exchange gone violently wrong. Rather than report the discovery to the police, Moss decides to simply take the two million dollars present for himself. This puts the psychopathic killer, Anton Chigurh (Javier Bardem), on his trail as he dispassionately murders nearly every rival, bystander and even employer in his pursuit of his quarry and the money. As Moss desperately attempts to keep one step ahead, the blood from this hunt begins to flow behind him with relentlessly growing intensity as Chigurh closes in. Meanwhile, the laconic Sheriff Ed Tom Bell (Tommy Lee Jones) blithely oversees the investigation even as he struggles to face the sheer enormity of the crimes he is attempting to thwart.', 'Ethan Coen, Joel Coen', 2007, 'https://upload.wikimedia.org/wikipedia/en/8/8b/No_Country_for_Old_Men_poster.jpg', ARRAY['Crime', 'Drama', 'Thriller']),
    ('b5e3da60-53eb-42a6-a6fb-73484ffee991', 'Zodiac', 'A serial killer in the San Francisco Bay Area taunts police with his letters and cryptic messages. We follow the investigators and reporters in this lightly fictionalized account of the true 1970s'' case as they search for the murderer, becoming obsessed with the case. Based on Robert Graysmith''s book, the movie''s focus is the lives and careers of the detectives and newspaper people.', 'David Fincher', 2007, 'https://upload.wikimedia.org/wikipedia/en/3/3a/Zodiac2007Poster.jpg', ARRAY['Crime', 'Drama', 'Mystery']),
    ('d3898c71-d4d3-48a4-a60b-f95beba8d2c7', 'Taxi Driver', 'Travis Bickle is an ex-Marine and Vietnam War veteran living in New York City. As he suffers from insomnia, he spends his time working as a taxi driver at night, watching porn movies at seedy cinemas during the day, or thinking about how the world, New York in particular, has deteriorated into a cesspool. He''s a loner who has strong opinions about what is right and wrong with mankind. For him, the one bright spot in humanity is Betsy, a worker on the presidential nomination campaign of Senator Charles Palantine. After an incident, he believes he has to do whatever he needs to make the world a better place.', 'Martin Scorsese', 1976, 'https://upload.wikimedia.org/wikipedia/en/3/33/Taxi_Driver_%281976_film_poster%29.jpg', ARRAY['Crime', 'Drama']),
    ('a97b3737-31ea-4106-bff0-111c170e558f', 'Heat', 'Hunters and their prey--Neil and his professional criminal crew hunt to score big money targets (banks, vaults, armored cars) and are, in turn, hunted by Lt. Vincent Hanna and his team of cops in the Robbery/Homicide police division. A botched job puts Hanna onto their trail while they regroup and try to put together one last big ''retirement'' score. Neil and Vincent are similar in many ways, including their troubled personal lives. At a crucial moment in his life, Neil disobeys the dictum taught to him long ago by his criminal mentor--''Never have anything in your life that you can''t walk out on in thirty seconds flat, if you spot the heat coming around the corner''--as he falls in love. Thus the stage is set for the suspenseful ending....', 'Michael Mann', 1995, 'https://upload.wikimedia.org/wikipedia/en/6/6c/Heatposter.jpg', ARRAY['Action', 'Crime', 'Drama']),
    ('124e874e-1e2c-47af-a4f6-f25104656d32', 'L.A. Confidential', '1950''s Los Angeles is the seedy backdrop for this intricate noir-ish tale of police corruption and Hollywood sleaze. Three very different cops are all after the truth, each in their own style: Ed Exley, the golden boy of the police force, willing to do almost anything to get ahead, except sell out; Bud White, ready to break the rules to seek justice, but barely able to keep his raging violence under control; and Jack Vincennes, always looking for celebrity and a quick buck until his conscience drives him to join Exley and White down the one-way path to find the truth behind the dark world of L.A. crime.', 'Curtis Hanson', 1997, 'https://upload.wikimedia.org/wikipedia/en/d/d8/La_confidential.jpg', ARRAY['Crime', 'Drama', 'Mystery']),
    ('1eaf06cf-ee38-44a8-9cf0-23f5d836b84d', 'Prisoners', 'How far would you go to protect your family? Keller Dover is facing every parent''s worst nightmare. His six-year-old daughter, Anna, is missing, together with her young friend, Joy, and as minutes turn to hours, panic sets in. The only lead is a dilapidated RV that had earlier been parked on their street. Heading the investigation, Detective Loki arrests its driver, Alex Jones, but a lack of evidence forces his release. As the police pursue multiple leads and pressure mounts, knowing his child''s life is at stake the frantic Dover decides he has no choice but to take matters into his own hands. But just how far will this desperate father go to protect his family?', 'Denis Villeneuve', 2013, 'https://upload.wikimedia.org/wikipedia/en/6/63/Prisoners2013Poster.jpg', ARRAY['Crime', 'Drama', 'Mystery']),
    ('e60bffa7-665f-4943-bc79-5c835648edb9', 'Schindler''s List', 'Oskar Schindler is a vain and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.', 'Steven Spielberg', 1994, 'https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg', ARRAY['Biography', 'Drama', 'History']),
    ('3b07e717-4246-42e6-b817-6643e98d238c', '12 Angry Men', 'The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors'' prejudices and preconceptions about the trial, the accused, AND each other. Based on the play, all of the action takes place on the stage of the jury room.', 'Sidney Lumet', 1957, 'https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg', ARRAY['Crime', 'Drama']),
    ('5de2b48f-6bf8-4f04-9098-29c026ac8e8c', 'There Will Be Blood', 'The intersecting life stories of Daniel Plainview and Eli Sunday in early twentieth century California is presented. Miner turn oilman Daniel Plainview is a driven man who will do whatever it takes to achieve his goals. He works hard but he also takes advantage of those around him at their expense if need be. His business partner is his son H.W., who in reality he "acquired" when H.W.''s biological single father, who worked on one of Daniel''s rigs, got killed in a workplace accident. Daniel is deeply protective of H.W. if only for what H.W. brings to the partnership. Eli Sunday is one in a pair of twins, whose family farm Daniel purchases for the major oil deposit located on it. Eli, the local preacher and a self-proclaimed faith healer, wants the money from the sale of the property to finance his own church. The lives of the two competitive men often clash as Daniel pumps oil off the property and tries to acquire all the surrounding land at bargain prices to be able to build a pipeline to the coast, and as Eli tries to build his own religious empire.', 'Paul Thomas Anderson', 2007, 'https://upload.wikimedia.org/wikipedia/en/d/da/There_Will_Be_Blood_Poster.jpg', ARRAY['Drama', 'History']),
    ('d485df39-7184-4944-bbcf-7e5f77ece8ab', 'Oppenheimer', 'A dramatization of the life story of J. Robert Oppenheimer, the physicist who had a large hand in the development of the atomic bomb, thus helping end World War 2. We see his life from university days all the way to post-WW2, where his fame saw him embroiled in political machinations.', 'Christopher Nolan', 2023, 'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg', ARRAY['Biography', 'Drama', 'History']),
    ('d940402f-7f3e-4acf-9b74-3a5a4f23bc39', 'The Social Network', 'On a fall night in 2003, Harvard undergrad and computer programming genius Mark Zuckerberg sits down at his computer and heatedly begins working on a new idea. In a fury of blogging and programming, what begins in his dorm room soon becomes a global social network and a revolution in communication. A mere six years and 500 million friends later, Mark Zuckerberg is the youngest billionaire in history... but for this entrepreneur, success leads to both personal and legal complications.', 'David Fincher', 2010, 'https://upload.wikimedia.org/wikipedia/en/8/8c/The_Social_Network_film_poster.png', ARRAY['Biography', 'Drama']),
    ('617e8a9a-6f89-494e-ad81-7e555fdf33ad', 'Good Will Hunting', 'A touching tale of a wayward young man who struggles to find his identity, living in a world where he can solve any problem, except the one brewing deep within himself, until one day he meets his soul mate who opens his mind and his heart.', 'Gus Van Sant', 1998, 'https://upload.wikimedia.org/wikipedia/en/5/52/Good_Will_Hunting.png', ARRAY['Drama', 'Romance']),
    ('4ae49160-8009-439a-ade1-9f4eca793af8', 'Dead Poets Society', 'Painfully shy Todd Anderson has been sent to the school where his popular older brother was valedictorian. His roommate, Neil Perry, although exceedingly bright and popular, is very much under the thumb of his overbearing father. The two, along with their other friends, meet Professor Keating, their new English teacher, who tells them of the Dead Poets Society, and encourages them to go against the status quo. Each does so in his own way, and is changed for life.', 'Peter Weir', 1989, 'https://upload.wikimedia.org/wikipedia/en/8/86/Dead_poets_society.png', ARRAY['Comedy', 'Drama']),
    ('60c25e56-b197-48bc-b6c4-30ba6c2d3617', 'A Clockwork Orange', 'Protagonist Alex DeLarge is an "ultraviolent" youth in futuristic Britain. As with all luck, his eventually runs out and he''s arrested and convicted of murder. While in prison, Alex learns of an experimental program in which convicts are programmed to detest violence. If he goes through the program, his sentence will be reduced and he will be back on the streets sooner than expected. But Alex''s ordeals are far from over once he hits the streets of Britain..', 'Stanley Kubrick', 1971, 'https://upload.wikimedia.org/wikipedia/en/7/73/A_Clockwork_Orange_%281971%29.png', ARRAY['Crime', 'Sci-Fi', 'Drama']),
    ('cc012572-871a-4f13-87c8-8928309680dc', 'The Lord of the Rings: The Fellowship of the Ring', 'An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to Mount Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir, and his three Hobbit friends Merry, Pippin, and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign.', 'Peter Jackson', 2001, 'https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg', ARRAY['Action', 'Adventure', 'Fantasy']),
    ('0cdb4e31-d19e-4d98-9289-f300e464ed2d', 'The Lord of the Rings: The Two Towers', 'The continuing quest of Frodo and the Fellowship to destroy the One Ring. Frodo and Sam discover they are being followed by the mysterious Gollum. Aragorn, the Elf archer Legolas, and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman''s deadly spell.', 'Peter Jackson', 2002, 'https://upload.wikimedia.org/wikipedia/en/a/a1/Lord_Rings_Two_Towers.jpg', ARRAY['Action', 'Adventure', 'Fantasy']),
    ('3a1ffef7-b704-44f8-839e-0c9a2784e4b3', 'Raiders of the Lost Ark', 'The year is 1936. An archeology professor named Indiana Jones is venturing in the jungles of South America searching for a golden statue. Unfortunately, he sets off a deadly trap but miraculously escapes. Then, Jones hears from a museum curator named Marcus Brody about a biblical artifact called The Ark of the Covenant, which can hold the key to human existence. Jones has to venture to vast places such as Nepal and Egypt to find this artifact. However, he will have to fight his enemy Rene Belloq and a band of Nazis in order to reach it.', 'Steven Spielberg', 1981, 'https://upload.wikimedia.org/wikipedia/en/a/a6/Raiders_of_the_Lost_Ark_Theatrical_Poster.jpg', ARRAY['Action', 'Adventure']),
    ('95d560dc-a7ee-4c96-a3a4-a8b0fa177db4', 'Die Hard', 'NYPD cop John McClane goes on a Christmas vacation to visit his wife Holly in Los Angeles where she works for the Nakatomi Corporation. While they are at the Nakatomi headquarters for a Christmas party, a group of robbers led by Hans Gruber take control of the building and hold everyone hostage, with the exception of John, while they plan to perform a lucrative heist. Unable to escape and with no immediate police response, John is forced to take matters into his own hands.', 'John McTiernan', 1988, 'https://upload.wikimedia.org/wikipedia/en/c/ca/Die_Hard_%281988_film%29_poster.jpg', ARRAY['Action', 'Thriller']),
    ('013afa04-dede-4b25-9c2f-f81dc6334dcc', 'Spider-Man 2', 'Peter Parker is an unhappy man: after two years of fighting crime as Spider-Man, his life has begun to fall apart. The girl he loves is engaged to someone else, his grades are slipping, he cannot keep any of his jobs, and on top of it, the newspaper Daily Bugle is attacking him viciously, claiming that Spider-Man is a criminal. He reaches the breaking point and gives up the crime fighter''s life, once and for all. But after a failed fusion experiment, eccentric and obsessive scientist Dr. Otto Octavius is transformed into super villain Doctor Octopus, Doc Ock for short, having four long tentacles as extra hands. Peter guesses it might just be time for Spider-Man to return, but would he act upon it?', 'Sam Raimi', 2004, 'https://upload.wikimedia.org/wikipedia/en/4/4e/Spider-Man_2_USA_poster.jpg', ARRAY['Action', 'Adventure', 'Sci-Fi']),
    ('a5a3f247-edd2-4355-9179-3eeed7ad688e', 'Avengers: Infinity War', 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment, the fate of Earth and existence has never been more uncertain.', 'Anthony Russo, Joe Russo', 2018, 'https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg', ARRAY['Action', 'Adventure', 'Sci-Fi']),
    ('4b4e9810-e9f2-4af8-b7e6-e6a02d0d483c', 'Mission: Impossible - Fallout', 'Two years after Ethan Hunt had successfully captured Solomon Lane, the remnants of the Syndicate have reformed into another organization called the Apostles. Under the leadership of a mysterious fundamentalist known only as John Lark, the organization is planning on acquiring three plutonium cores. Ethan and his team are sent to Berlin to intercept them, but the mission fails when Ethan saves Luther and the Apostles escape with the plutonium. With CIA agent August Walker joining the team, Ethan and his allies must now find the plutonium cores before it''s too late.', 'Christopher McQuarrie', 2018, 'https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg', ARRAY['Action', 'Adventure', 'Thriller']),
    ('8dec50c1-eb6e-4bcf-8e74-08c915626c2e', 'Logan', 'In 2029 the mutant population has shrunken significantly due to genetically modified plants designed to reduce mutant powers and the X-Men have disbanded. Logan, whose power to self-heal is dwindling, has surrendered himself to alcohol and now earns a living as a chauffeur. He takes care of the ailing old Professor X whom he keeps hidden away. One day, a female stranger asks Logan to drive a girl named Laura to the Canadian border. At first he refuses, but the Professor has been waiting for a long time for her to appear. Laura possesses an extraordinary fighting prowess and is in many ways like Wolverine. She is pursued by sinister figures working for a powerful corporation; this is because they made her, with Logan''s DNA. A decrepit Logan is forced to ask himself if he can or even wants to put his remaining powers to good use. It would appear that in the near-future, the times in which they were able put the world to rights with razor sharp claws and telepathic powers are now over.', 'James Mangold', 2017, 'https://upload.wikimedia.org/wikipedia/en/3/37/Logan_2017_poster.jpg', ARRAY['Action', 'Drama', 'Sci-Fi']),
    ('86a01058-d177-4e12-8c76-4b342bc0654a', 'Kill Bill: Vol. 1', 'Four years after taking a bullet in the head at her own wedding, The Bride emerges from a coma and decides it''s time for payback... with a vengeance. Having been gunned down by her former boss Bill and his deadly squad of international assassins, it''s a kill-or-be-killed fight she didn''t start, but is determined to finish.', 'Quentin Tarantino', 2003, 'https://upload.wikimedia.org/wikipedia/en/2/2c/Kill_Bill_Volume_1.png', ARRAY['Action', 'Crime', 'Thriller']),
    ('6786358b-c2f9-4bb4-a8d4-25b301aebf00', 'Princess Mononoke', 'While protecting his village from rampaging boar-god/demon, a confident young warrior, Ashitaka, is stricken by a deadly curse. To save his life, he must journey to the forests of the west. Once there, he''s embroiled in a fierce campaign that humans were waging on the forest. The ambitious Lady Eboshi and her loyal clan use their guns against the gods of the forest and a brave young woman, Princess Mononoke, who was raised by a wolf-god. Ashitaka sees the good in both sides and tries to stem the flood of blood. This is met by animosity by both sides as they each see him as supporting the enemy.', 'Hayao Miyazaki', 1997, 'https://upload.wikimedia.org/wikipedia/en/8/8c/Princess_Mononoke_Japanese_poster.png', ARRAY['Animation', 'Action', 'Adventure']),
    ('917540b2-a19d-411b-ba0a-b244164eb320', 'Akira', '2019. 31 years after being destroyed during World War 3, Tokyo (now ''Neo-Tokyo'') has been rebuilt and is a thriving metropolis. Shotaro Kaneda is the leader of a biker gang. His friend Tetsuo is injured in an accident and taken to a top-secret government facility. He develops telekinetic powers but decides to use them for evil rather than good. He has the same powers as Akira, the force that destroyed Tokyo in 1988, and now it appears that history will repeat itself.', 'Katsuhiro Ôtomo', 1988, 'https://upload.wikimedia.org/wikipedia/en/5/5d/AKIRA_%281988_poster%29.jpg', ARRAY['Animation', 'Action', 'Sci-Fi']),
    ('8b54a438-2f86-4d3a-878b-d568d41e0481', 'Ghost in the Shell', 'In the near future, human organs are enhanced by the cybernetics technology developed by the powerful Hanka Robotics Corporation owned by Cutter. Dr. Ouelet is responsible for the development of the secret project 2571 of a full mechanical body to be connected to a human brain. She uses the brain of a young woman that lost her parents in a cyber attack as subject of a prototype. One year later, the woman is ranked Major and has joined Section 9, an anti-terrorist division commanded by Chief Daisuke Aramaki, working with agents Batou and Togusa. She needs to use a medicine to help the integration of her brain with the mechanical body and has no recollections of her previous life. When Section 9 hunts down the terrorist Kuze, Major learns the secrets about Hanka Robotics and the experiment she was subjected. Now she faces her ultimate enemy: Kuze, a criminal who has managed to hack into the brains of androids and control them.', 'Rupert Sanders', 2017, 'https://upload.wikimedia.org/wikipedia/en/1/11/Ghost_in_the_Shell_%282017_film%29.png', ARRAY['Animation', 'Action', 'Sci-Fi']),
    ('5a83b348-edca-4821-beda-f4e591d27b9e', 'Spider-Man: Across the Spider-Verse', 'Miles Morales returns for the next chapter of the Oscar®-winning Spider-Verse saga, an epic adventure that will transport Brooklyn''s full-time, friendly neighborhood Spider-Man across the Multiverse to join forces with Gwen Stacy and a new team of Spider-People to face off with a villain more powerful than anything they have ever encountered.', 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson', 2023, 'https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg', ARRAY['Animation', 'Action', 'Adventure']),
    ('f03cb178-179f-4499-a0e1-cc3938e08654', 'The Iron Giant', 'This is the story of a nine-year-old boy named Hogarth Hughes who makes friends with an innocent alien giant robot that came from outer space. Meanwhile, a paranoid U.S. Government agent named Kent Mansley arrives in town, determined to destroy the giant at all costs. It''s up to Hogarth to protect him by keeping him at Dean McCoppin''s place in the junkyard.', 'Brad Bird', 1999, 'https://upload.wikimedia.org/wikipedia/en/d/d3/The_Iron_Giant_poster.JPG', ARRAY['Animation', 'Action', 'Family']),
    ('893a32dd-d4ea-4d42-8047-10d913a4753c', 'The Thing', 'A US research station, Antarctica, early-winter 1982. The base is suddenly buzzed by a helicopter from the nearby Norwegian research station. They are trying to kill a dog that has escaped from their base. After the destruction of the Norwegian chopper the members of the US team fly to the Norwegian base, only to discover them all dead or missing. They do find the remains of a strange creature the Norwegians burned. The Americans take it to their base and deduce that it is an alien life form. After a while it is apparent that the alien can take over and assimilate into other life forms, including humans, and can spread like a virus. This means that anyone at the base could be inhabited by The Thing, and tensions escalate.', 'John Carpenter', 1982, 'https://upload.wikimedia.org/wikipedia/en/e/e3/The_Thing_%281982_film%29.png', ARRAY['Horror', 'Mystery', 'Sci-Fi']),
    ('e567f16e-1378-449d-9fa9-0975565eb043', 'Get Out', 'Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family''s overly accommodating behavior as nervous attempts to deal with their daughter''s interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.', 'Jordan Peele', 2017, 'https://upload.wikimedia.org/wikipedia/en/a/a3/Get_Out_poster.png', ARRAY['Horror', 'Mystery', 'Thriller']),
    ('a9e59a5f-76d4-48c2-bedf-ced00319f0b0', 'La La Land', 'Aspiring actress serves lattes to movie stars in between auditions and jazz musician Sebastian scrapes by playing cocktail-party gigs in dingy bars. But as success mounts, they are faced with decisions that fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.', 'Damien Chazelle', 2016, 'https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png', ARRAY['Comedy', 'Drama', 'Music']);


-- Additional 39 movies
INSERT INTO movies (id, title, synopsis, director, release_year, poster_url, genres) VALUES
    ('a1b2c3d4-0001-0000-0000-000000000001', 'The Green Mile', 'When a giant of a man named John Coffey is brought to death row, he brings with him a supernatural gift that changes the lives of the guards who oversee him. Despite his imposing size and the horrific nature of his alleged crimes, Coffey exhibits a gentle, childlike demeanor and extraordinary healing abilities. As the head guard, Paul Edgecomb, grapples with Coffey''s miraculous powers and impending execution, he must question his own beliefs about guilt, redemption, and the true nature of miracles in a dark world.', 'Frank Darabont', 1999, 'https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg', ARRAY['Crime', 'Drama', 'Fantasy']),
    ('a1b2c3d4-0002-0000-0000-000000000002', 'Forrest Gump', 'Slow-witted but incredibly kindhearted Forrest Gump leads a truly extraordinary life, inadvertently finding himself at the center of some of the most pivotal events of the 20th century. From teaching Elvis how to dance and becoming a college football star, to fighting in the Vietnam War and exposing the Watergate scandal, Forrest''s innocent perspective provides a unique lens on a changing America. Despite his remarkable achievements, his only true desire is to reunite with his childhood sweetheart, Jenny, whose troubled life constantly pulls her away from him.', 'Robert Zemeckis', 1994, 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', ARRAY['Drama', 'Romance', 'Comedy']),
    ('a1b2c3d4-0003-0000-0000-000000000003', 'Fight Club', 'A chronically depressed and insomniac office worker seeks an escape from his mundane, consumerist life. He crosses paths with Tyler Durden, a charismatic and nihilistic soap salesman who introduces him to the visceral thrill of bare-knuckle fighting. Together, they form a secret, underground ''Fight Club'' that rapidly evolves into a sprawling, anti-capitalist terrorist organization known as Project Mayhem. As Tyler''s actions become increasingly radical and dangerous, the narrator is forced to confront the horrifying reality of the monster he has helped unleash.', 'David Fincher', 1999, 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', ARRAY['Drama', 'Thriller', 'Action']),
    ('a1b2c3d4-0004-0000-0000-000000000004', 'The Lord of the Rings: The Return of the King', 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'Peter Jackson', 2003, 'https://upload.wikimedia.org/wikipedia/en/4/48/Lord_Rings_Return_King.jpg', ARRAY['Action', 'Adventure', 'Drama']),
    ('a1b2c3d4-0005-0000-0000-000000000005', 'Star Wars: Episode V - The Empire Strikes Back', 'Following a devastating defeat at the hands of the Empire on the icy planet of Hoth, the Rebel Alliance is scattered across the galaxy. While Han Solo, Princess Leia, and Chewbacca desperately flee from the relentless pursuit of Darth Vader and his bounty hunters, Luke Skywalker travels to the swamp planet of Dagobah to train under the ancient Jedi Master, Yoda. As Luke struggles to master the Force, he is inexorably drawn into a confrontation with Vader, leading to a dark and shocking revelation that will change his destiny forever.', 'Irvin Kershner', 1980, 'https://upload.wikimedia.org/wikipedia/en/3/3f/The_Empire_Strikes_Back_%281980_film%29.jpg', ARRAY['Action', 'Adventure', 'Sci-Fi']),
    ('a1b2c3d4-0006-0000-0000-000000000006', 'The Silence of the Lambs', 'Clarice Starling, a brilliant but inexperienced FBI trainee, is assigned to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath serving life behind bars for various acts of murder and cannibalism. The FBI hopes that Lecter''s insight into the twisted minds of killers will help them track down ''Buffalo Bill'', an active serial killer who skins his female victims. As Starling engages in a tense psychological game of cat-and-mouse with Lecter, she must confront her own deep-seated traumas to stop the killer before he claims his next victim.', 'Jonathan Demme', 1991, 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1YWEtNDQwZjY5ZTA1ZWEzXkEyXkFqcGc@._V1_SX1000.jpg', ARRAY['Crime', 'Drama', 'Thriller']),
    ('a1b2c3d4-0007-0000-0000-000000000007', 'Leon: The Professional', 'Léon is a highly skilled and solitary hitman living a quiet life in New York City, interacting only with his boss and his beloved houseplant. His isolated existence is shattered when a corrupt DEA agent murders the dysfunctional family living next door. The only survivor is 12-year-old Mathilda, who begs Léon to take her in and teach her the deadly skills of his trade so she can avenge her four-year-old brother. An unlikely and poignant bond forms between the hardened killer and the traumatized young girl as they become targets themselves.', 'Luc Besson', 1994, 'https://upload.wikimedia.org/wikipedia/en/0/03/Leon-poster.jpg', ARRAY['Action', 'Crime', 'Drama']),
    ('a1b2c3d4-0008-0000-0000-000000000008', 'Spirited Away', 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.', 'Hayao Miyazaki', 2001, 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNTEhXkEyXkFqcGc@._V1_SX1000.jpg', ARRAY['Animation', 'Adventure', 'Family']),
    ('a1b2c3d4-0009-0000-0000-000000000009', 'City Lights', 'The Tramp, a penniless but deeply romantic vagabond, falls deeply in love with a beautiful, blind flower girl who mistakenly believes him to be a wealthy duke. Determined to help her, he embarks on a series of hilarious and chaotic misadventures—including working as a street sweeper and participating in a disastrous boxing match—to earn the money needed for a medical operation that could restore her sight. Along the way, he also repeatedly saves the life of an eccentric millionaire who is only generous when intoxicated.', 'Charles Chaplin', 1931, 'https://upload.wikimedia.org/wikipedia/commons/0/09/City_Lights_%281931_theatrical_poster_-_retouched%29.jpg', ARRAY['Comedy', 'Drama', 'Romance']),
    ('a1b2c3d4-0010-0000-0000-000000000010', 'Life Is Beautiful', 'In 1930s Italy, Guido, a Jewish Italian bookshop owner, uses his vibrant imagination and irrepressible humor to build a beautiful life for his beloved wife and young son, Giosué. When their happiness is abruptly shattered by the outbreak of World War II and they are sent to a Nazi concentration camp, Guido goes to incredible lengths to protect his son from the horrors around them. He fabricates an elaborate game, convincing Giosué that the camp is merely a complex competition where the ultimate prize is a real tank, demonstrating the extraordinary power of a father''s love.', 'Roberto Benigni', 1997, 'https://image.tmdb.org/t/p/w500/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg', ARRAY['Comedy', 'Drama', 'War']),
    ('a1b2c3d4-0011-0000-0000-000000000011', 'Se7en', 'In a bleak, rain-soaked city plagued by crime and moral decay, retiring police detective William Somerset is paired with a hot-headed, idealistic young transfer, David Mills. Together, they are thrust into a horrific investigation tracking a brilliant and elusive serial killer who meticulously murders his victims according to the Seven Deadly Sins. As the detectives delve deeper into the killer''s gruesome and intellectual labyrinth, the case begins to take a devastating psychological toll, building towards a shocking and unforgettable climax.', 'David Fincher', 1995, 'https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg', ARRAY['Crime', 'Drama', 'Mystery']),
    ('a1b2c3d4-0012-0000-0000-000000000012', 'It's a Wonderful Life', 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.', 'Frank Capra', 1946, 'https://image.tmdb.org/t/p/w500/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg', ARRAY['Drama', 'Family', 'Fantasy']),
    ('a1b2c3d4-0013-0000-0000-000000000013', 'Star Wars: Episode IV - A New Hope', 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire''s world-destroying battle station.', 'George Lucas', 1977, 'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', ARRAY['Action', 'Adventure', 'Fantasy']),
    ('a1b2c3d4-0014-0000-0000-000000000014', 'Saving Private Ryan', 'Following the harrowing and bloody Allied invasion of Omaha Beach during World War II, Captain John Miller is tasked with leading a squad of soldiers on a highly dangerous and controversial mission behind enemy lines. Their objective is to locate and extract Private James Ryan, a paratrooper whose three brothers have all been killed in combat within days of each other. As the squad pushes deeper into war-torn France, facing constant peril and moral dilemmas, they are forced to question the value of risking eight lives to save just one.', 'Steven Spielberg', 1998, 'https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg', ARRAY['Drama', 'War', 'Action']),
    ('a1b2c3d4-0015-0000-0000-000000000015', 'The Prestige', 'In late 19th-century London, Robert Angier and Alfred Borden are rival stage magicians whose intense competition turns into a bitter, lifelong obsession after a tragic accident during a water escape trick. Driven by a desire for vengeance and supremacy, the two men constantly attempt to sabotage one another''s performances and steal each other''s secrets. Their escalating feud leads them down a dark and destructive path involving science, sacrifice, and betrayal, culminating in the pursuit of the ultimate illusion: the teleporting ''Transported Man''.', 'Christopher Nolan', 2006, 'https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg', ARRAY['Drama', 'Mystery', 'Thriller']),
    ('a1b2c3d4-0016-0000-0000-000000000016', 'The Departed', 'In South Boston, the state police force is waging an all-out war to take down the city''s top organized crime syndicate, led by the ruthless and intelligent mob boss Frank Costello. A young undercover cop, Billy Costigan, successfully infiltrates Costello''s crew, while simultaneously, a hardened young criminal, Colin Sullivan, has infiltrated the police department as an informer for the syndicate. As both men become deeply consumed by their double lives, it becomes a desperate race against time to uncover the identity of the other mole before their own covers are blown.', 'Martin Scorsese', 2006, 'https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg', ARRAY['Crime', 'Drama', 'Thriller']),
    ('a1b2c3d4-0018-0000-0000-000000000018', 'The Lion King', 'In the vibrant Pride Lands of Africa, a young lion cub named Simba idolizes his father, King Mufasa, and eagerly anticipates his own royal destiny. However, Simba''s envious and treacherous uncle, Scar, plots to usurp the throne by orchestrating a tragic stampede that claims Mufasa''s life and forces Simba into exile. After growing up in the jungle with his carefree friends Timon and Pumbaa, an adult Simba must confront his past, embrace his responsibilities, and return to challenge Scar to reclaim his rightful place in the Circle of Life.', 'Roger Allers', 1994, 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg', ARRAY['Animation', 'Adventure', 'Family']),
    ('a1b2c3d4-0019-0000-0000-000000000019', 'Whiplash', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student''s potential.', 'Damien Chazelle', 2014, 'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtNDVrcS00YTU5LWJmOTItM2NlNGI3MTIzNDRlXkEyXkFqcGc@._V1_SX1000.jpg', ARRAY['Drama', 'Music']),
    ('a1b2c3d4-0020-0000-0000-000000000020', 'The Pianist', 'Based on a true story, the film follows Wladyslaw Szpilman, a brilliant Polish-Jewish pianist working for Warsaw radio at the outbreak of World War II. As the Nazi occupation of Poland intensifies, Szpilman and his family are forced into the crowded and squalid Warsaw Ghetto. Separated from his loved ones and facing constant starvation, disease, and the threat of deportation to extermination camps, Szpilman must rely on the kindness of strangers, his own survival instincts, and the enduring power of music to stay alive in the ruins of a devastated city.', 'Roman Polanski', 2002, 'https://upload.wikimedia.org/wikipedia/en/a/a6/The_Pianist_movie.jpg', ARRAY['Biography', 'Drama', 'Music']),
    ('a1b2c3d4-0021-0000-0000-000000000021', 'The Usual Suspects', 'Following a massive explosion on a ship docked in San Pedro Bay that leaves 27 dead and $91 million in drug money missing, customs agent Dave Kujan interrogates the sole survivor, a mild-mannered con artist with cerebral palsy named Verbal Kint. Through an intricate series of flashbacks, Verbal recounts how he and four other career criminals were brought together in a police lineup and subsequently forced into a heist orchestrated by the legendary, almost mythical criminal mastermind known as Keyser Söze, building to a legendary twist.', 'Bryan Singer', 1995, 'https://upload.wikimedia.org/wikipedia/en/9/9c/Usual_suspects_ver1.jpg', ARRAY['Crime', 'Mystery', 'Thriller']),
    ('a1b2c3d4-0022-0000-0000-000000000022', 'Back to the Future', 'Marty McFly is a typical American teenager of the 1980s who is accidentally sent back to the year 1955 in a plutonium-powered DeLorean time machine invented by his eccentric scientist friend, Doc Brown. During his trip back in time, Marty inadvertently interferes with his teenage parents'' first meeting, threatening his own existence. Now, he must race against time to ensure his parents fall in love and find a way to harness a bolt of lightning to power the time machine and return to 1985 before he is erased from history.', 'Robert Zemeckis', 1985, 'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg', ARRAY['Adventure', 'Comedy', 'Sci-Fi']),
    ('a1b2c3d4-0023-0000-0000-000000000023', 'Modern Times', 'In a poignant and hilarious critique of the machine age, the iconic Little Tramp struggles to survive in a modern, heavily industrialized world. Employed on an accelerating assembly line, he suffers a nervous breakdown that leads to a stint in a mental hospital and a series of arrests. Along the way, he meets and falls in love with a beautiful, orphaned gamine who is fleeing the authorities. Together, the two outcasts attempt to navigate the harsh realities of the Great Depression, dreaming of a simple, stable life amidst the chaos of modernity.', 'Charles Chaplin', 1936, 'https://image.tmdb.org/t/p/w500/7uoiKOEjxBBW0AgDGQWrlfGQ90w.jpg', ARRAY['Comedy', 'Drama', 'Romance']),
    ('a1b2c3d4-0024-0000-0000-000000000024', 'Terminator 2: Judgment Day', 'More than a decade after the first Terminator attempted to alter the future, a new, highly advanced shape-shifting cyborg known as the T-1000 is sent back in time to kill ten-year-old John Connor, the future leader of the human resistance. In a twist of fate, the resistance sends back a reprogrammed version of the original T-800 model to protect the boy. Joined by John''s fiercely hardened mother, Sarah, the trio must fight against seemingly impossible odds to destroy the T-1000 and prevent ''Judgment Day'', the impending nuclear apocalypse orchestrated by the AI Skynet.', 'James Cameron', 1991, 'https://upload.wikimedia.org/wikipedia/en/5/5e/Terminator_2-Judgment_Day.png', ARRAY['Action', 'Sci-Fi', 'Thriller']),
    ('a1b2c3d4-0025-0000-0000-000000000025', 'Psycho', 'A Phoenix secretary embezzles $40,000 from her employer''s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.', 'Alfred Hitchcock', 1960, 'https://upload.wikimedia.org/wikipedia/commons/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg', ARRAY['Horror', 'Mystery', 'Thriller']),
    ('a1b2c3d4-0026-0000-0000-000000000026', 'Alien', 'After a space merchant vessel receives an unknown transmission as a distress call, one of the crew''s members is attacked by a mysterious life form.', 'Ridley Scott', 1979, 'https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGc@._V1_SX1000.jpg', ARRAY['Horror', 'Sci-Fi']),
    ('a1b2c3d4-0027-0000-0000-000000000027', 'City of God', 'In the slums of Rio, two kids'' paths diverge as one struggles to become a photographer and the other a kingpin.', 'Fernando Meirelles', 2002, 'https://upload.wikimedia.org/wikipedia/en/1/10/CidadedeDeus.jpg', ARRAY['Crime', 'Drama']),
    ('a1b2c3d4-0028-0000-0000-000000000028', 'Django Unchained', 'In the antebellum South, a German dentist-turned-bounty hunter named Dr. King Schultz acquires and frees an enslaved man named Django to help him track down a group of murderous outlaws. In exchange, Schultz promises to help Django locate and rescue his beloved wife, Broomhilda, who was sold to a different owner. Their bloody and vengeful journey eventually leads them to the notorious Candyland plantation, run by the charismatic but utterly cruel and sadistic Francophile, Calvin Candie, where they must use deception and extreme violence to achieve their goals.', 'Quentin Tarantino', 2012, 'https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg', ARRAY['Drama', 'Western', 'Action']),
    ('a1b2c3d4-0029-0000-0000-000000000029', 'Gladiator', 'Maximus is a powerful Roman general, loved by the people and the aging Emperor, Marcus Aurelius. Before his death, the Emperor chooses Maximus to be his heir over his own son, Commodus, and a power struggle leaves Maximus and his family condemned to death. The powerful general is captured and put into the Gladiator games until he dies. The only desire that fuels him now is the chance to rise to the top so that he will be able to look into the eyes of the man who will feel his revenge.', 'Ridley Scott', 2000, 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png', ARRAY['Action', 'Adventure', 'Drama']),
    ('a1b2c3d4-0030-0000-0000-000000000030', 'Memento', 'A man with short-term memory loss attempts to track down his wife''s murderer.', 'Christopher Nolan', 2000, 'https://upload.wikimedia.org/wikipedia/en/c/c7/Memento_poster.jpg', ARRAY['Mystery', 'Thriller']),
    ('a1b2c3d4-0031-0000-0000-000000000031', 'WALL·E', 'In the year 2805, Earth is a desolate, garbage-strewn wasteland abandoned by humanity, with only a solitary, rusty waste-collecting robot named WALL-E left to clean up the mess. WALL-E''s lonely, repetitive existence is turned upside down when he encounters EVE, a sleek and highly advanced reconnaissance robot sent to search for signs of sustainable life. Smitten by her, WALL-E follows EVE across the galaxy on an incredible, visually stunning adventure that will ultimately determine the future of mankind and their relationship with the planet they left behind.', 'Andrew Stanton', 2008, 'https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg', ARRAY['Animation', 'Adventure', 'Family']),
    ('a1b2c3d4-0032-0000-0000-000000000032', 'The Lives of Others', 'Set in East Berlin in 1984, five years before the fall of the Berlin Wall, the film follows Gerd Wiesler, a dedicated and emotionless interrogator and surveillance officer for the Stasi, the feared East German secret police. He is assigned to spy on Georg Dreyman, a successful playwright, and his actress lover, Christa-Maria Sieland. As Wiesler meticulously monitors their every word and action, he unexpectedly finds himself increasingly drawn to their passionate and artistic world, leading to a profound crisis of conscience that challenges his loyalty to the oppressive regime.', 'Florian Henckel von Donnersmarck', 2006, 'https://upload.wikimedia.org/wikipedia/en/9/9f/Leben_der_anderen.jpg', ARRAY['Drama', 'Mystery', 'Thriller']),
    ('a1b2c3d4-0033-0000-0000-000000000033', 'The Shining', 'Seeking solitude to write a new novel, recovering alcoholic Jack Torrance takes a job as the winter caretaker of the sprawling, isolated Overlook Hotel in the Colorado mountains, bringing along his wife, Wendy, and their young son, Danny. As the harsh winter traps them inside, the hotel''s dark, malevolent supernatural forces begin to prey on Jack''s fragile sanity, slowly driving him towards homicidal madness. Meanwhile, Danny, who possesses a unique telepathic gift called ''the shining'', is plagued by horrific visions of the hotel''s bloody past and the terrifying danger his father is becoming.', 'Stanley Kubrick', 1980, 'https://m.media-amazon.com/images/M/MV5BZWFlYmY2MWEtM2ZlMi00ZWM1LWI0MTQtYjc0ZmVmNTVkMGFlXkEyXkFqcGc@._V1_SX1000.jpg', ARRAY['Drama', 'Horror', 'Thriller']),
    ('a1b2c3d4-0034-0000-0000-000000000034', 'Paths of Glory', 'During World War I, a French general orders a seemingly impossible and suicidal assault on a heavily fortified German stronghold known as the ''Anthill.'' When the attack inevitably fails and the exhausted troops refuse to leave their trenches, the infuriated general demands that three soldiers be chosen at random to be court-martialed and executed for cowardice as an example to the rest of the army. Colonel Dax, an idealistic commanding officer who led the failed charge, bravely steps forward to act as their defense attorney in a deeply flawed military trial.', 'Stanley Kubrick', 1957, 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Paths_of_Glory_%281957_poster%29.jpg', ARRAY['Drama', 'War', 'History']),
    ('a1b2c3d4-0035-0000-0000-000000000035', 'Sunset Blvd.', 'Joe Gillis, a struggling, debt-ridden Hollywood screenwriter, accidentally stumbles into the crumbling mansion of Norma Desmond, an aging and deeply delusional former silent film star who has been largely forgotten by the industry. Desperate for a comeback, Norma hires Joe to edit her massive, unproduceable screenplay. Joe becomes increasingly trapped in her opulent, claustrophobic world of faded glory, manic depression, and obsession, leading to a complex and ultimately tragic relationship that serves as a dark, cynical critique of the Hollywood dream factory.', 'Billy Wilder', 1950, 'https://upload.wikimedia.org/wikipedia/commons/1/14/Sunset_Boulevard_%281950_poster%29.jpg', ARRAY['Drama', 'Film-Noir', 'Thriller']),
    ('a1b2c3d4-0036-0000-0000-000000000036', 'Witness for the Prosecution', 'Sir Wilfrid Robarts, an aging and ailing but brilliant London barrister, takes on the seemingly impossible defense of Leonard Vole, a charming and unemployed inventor who is accused of murdering a wealthy older woman who had recently made him the primary beneficiary of her will. The case hinges on the testimony of Leonard''s enigmatic German wife, Christine, who shockingly decides to testify not for the defense, but as a witness for the prosecution. The courtroom drama unfolds with a series of brilliant legal maneuvers, unexpected twists, and shocking revelations.', 'Billy Wilder', 1957, 'https://upload.wikimedia.org/wikipedia/en/c/cf/Witness_for_the_Prosecution_%281957_film%29_poster.jpg', ARRAY['Crime', 'Drama', 'Mystery']),
    ('a1b2c3d4-0037-0000-0000-000000000037', 'Aliens', 'After floating in hypersleep for 57 years, Ellen Ripley is rescued, only to find that her terrifying account of the lethal alien creature that wiped out her crew is met with deep skepticism by corporate executives. When communication is lost with a newly established terraforming colony on the very moon where the alien was first discovered, Ripley reluctantly agrees to accompany a heavily armed squad of Colonial Marines to investigate. What begins as a rescue mission quickly escalates into a desperate, all-out war for survival against a massive hive of the horrific creatures.', 'James Cameron', 1986, 'https://upload.wikimedia.org/wikipedia/en/f/fb/Aliens_poster.jpg', ARRAY['Action', 'Adventure', 'Sci-Fi']),
    ('a1b2c3d4-0038-0000-0000-000000000038', 'American Beauty', 'A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter''s best friend.', 'Sam Mendes', 1999, 'https://upload.wikimedia.org/wikipedia/en/9/9a/American_Beauty_1999_film_poster.jpg', ARRAY['Drama']),
    ('a1b2c3d4-0039-0000-0000-000000000039', 'Dr. Strangelove', 'In this brilliant and biting political satire, an unhinged and paranoid U.S. Air Force General, Jack D. Ripper, unilaterally orders a preemptive nuclear strike against the Soviet Union, believing that the communists are polluting the ''precious bodily fluids'' of the American people. As the bomber squadron nears its targets, the U.S. President, along with a frantic War Room full of politicians and military brass, including the eccentric ex-Nazi scientist Dr. Strangelove, desperately attempts to recall the planes and avert a global nuclear holocaust orchestrated by the ultimate doomsday machine.', 'Stanley Kubrick', 1964, 'https://upload.wikimedia.org/wikipedia/en/e/e6/Dr._Strangelove_poster.jpg', ARRAY['Comedy', 'War', 'Sci-Fi']);
-- seed reviewsINSERT INTO reviews (user_id, movie_id, rating, review_text) VALUES
    ('33333333-3333-3333-3333-333333333333', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 5, 'The definitive gangster film. Every scene is perfect.'),
    ('44444444-4444-4444-4444-444444444444', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 4, 'A bit slow at times, but undeniably great.'),
    ('55555555-5555-5555-5555-555555555555', 'cccccccc-cccc-cccc-cccc-cccccccccccc', 5, 'A timeless story of hope.'),
    ('11111111-1111-1111-1111-111111111111', 'cccccccc-cccc-cccc-cccc-cccccccccccc', 5, 'So incredibly moving. Must watch.'),
    ('22222222-2222-2222-2222-222222222222', 'dddddddd-dddd-dddd-dddd-dddddddddddd', 5, 'Heath Ledger''s Joker is legendary.'),
    ('33333333-3333-3333-3333-333333333333', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 4, 'Mind-bending, complex, and rewarding.'),
    ('44444444-4444-4444-4444-444444444444', 'ffffffff-ffff-ffff-ffff-ffffffffffff', 5, 'A biting social commentary wrapped in a thriller.'),
    ('55555555-5555-5555-5555-555555555555', '1a1a1a1a-1a1a-1a1a-1a1a-1a1a1a1a1a1a', 5, 'Visually stunning with an emotional core.'),
    ('11111111-1111-1111-1111-111111111111', '2b2b2b2b-2b2b-2b2b-2b2b-2b2b2b2b2b2b', 4, 'Tarantino''s dialogue is unmatched.'),
    ('33333333-3333-3333-3333-333333333333', '4d4d4d4d-4d4d-4d4d-4d4d-4d4d4d4d4d4d', 5, 'Revolutionary sci-fi.'),
    ('44444444-4444-4444-4444-444444444444', '5e5e5e5e-5e5e-5e5e-5e5e-5e5e5e5e5e5e', 5, 'Best animated film in years.'),
    ('55555555-5555-5555-5555-555555555555', '6f6f6f6f-6f6f-6f6f-6f6f-6f6f6f6f6f6f', 4, 'Epic world-building.');
